version: "3.3"

services:
  app:
    container_name: sz-mirror
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "20:20"
      - "2020:2020"
